opam-version: "2.0"
name: "amlc"
version: "0.1.0~preview"
synopsis: "Applied ML compiler and local AML executor"
maintainer: "Octra Labs"
authors: ["Octra Labs"]
depends: [
  "ocaml" {= "4.14.2"}
  "dune" {>= "3.0"}
  "zarith"
  "base64"
  "digestif"
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]